<#
.SYNOPSIS
    Start the Claudefuscator agent automatically when you log on (Windows).

.DESCRIPTION
    The agent is a loopback service: the Chrome extension resolves values
    through it, and the Claude Code mod collects its key and identifier list
    from it. Both want it running whenever you are working, which is a job for
    the operating system rather than for either of them.

    In particular the mod must NOT be the thing that starts it. The extension
    needs the agent when Claude Code is not running at all, so tying the
    agent's lifetime to a Claude Code session would leave the browser unable
    to unveil anything the moment you closed the terminal.

    TWO DECISIONS WORTH KNOWING ABOUT

    1. It runs through wscript.exe, not powershell.exe.

       A scheduled task flashes a console window on every start, and
       -WindowStyle Hidden does not prevent it: the console is created by the
       loader from the host binary's PE subsystem field, before any argument
       is parsed. powershell.exe and pwsh.exe are both console binaries;
       wscript.exe is a GUI binary. The host decides, not the flag.

    2. It runs as you, interactively, not "whether logged on or not".

       The second option sounds better and is wrong here. It logs on with S4U,
       which cannot decrypt your DPAPI master key - and the agent's vault
       credential is protected with DPAPI. The task would start, fail to open
       the credential, and the agent would run without a vault while looking
       perfectly healthy. An interactive logon trigger keeps the credential
       readable, and the agent is only useful while you are logged in anyway.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File tools\windows\install-autostart.ps1
#>
[CmdletBinding()]
param(
    [string] $TaskName = 'Claudefuscator agent',
    [string] $Python,
    [switch] $StartNow
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$agent = Join-Path $repoRoot 'agent\claudefuscator_agent.py'

if (-not (Test-Path $agent)) {
    throw "Cannot find the agent at $agent. Run this from a checkout of the repository."
}

if (-not $Python) {
    $Python = (Get-Command python -ErrorAction SilentlyContinue).Source
}
if (-not $Python) {
    throw 'No python on PATH. Pass -Python "C:\path\to\python.exe".'
}

$stateDir = Join-Path $env:USERPROFILE '.claudefuscator'
New-Item -ItemType Directory -Force -Path $stateDir | Out-Null

$log = Join-Path $stateDir 'agent.log'
$vbs = Join-Path $stateDir 'start-agent.vbs'

# Absolute paths baked in at install time rather than derived at run time:
# the task runs with no working directory of consequence, and a relative
# path here fails in a way that only shows up as an empty log.
#
# Quotes are assembled with Chr(34) rather than written inline. A literal
# quote inside a VBScript string has to be DOUBLED, and writing the paths
# in directly produced a file that terminated its string early - wscript
# exited 1 and the only symptom was a task reporting LastTaskResult 1 with
# nothing in the log, because the agent never started.
#
# The doubled opening quote is cmd's rule, not a mistake: given a command
# line that begins with a quote, cmd /c strips the first and last one and
# runs the rest, so the real command needs its own pair inside.
#
# -u because the startup banner is buffered otherwise, and a log that stays
# empty for the first minute reads as "it did not start".
$vbsBody = @"
Option Explicit
' Generated by tools\windows\install-autostart.ps1. Edit that, not this.
'
' wscript.exe is a GUI-subsystem binary, which is the only reason no console
' window appears. Launching the same command from powershell.exe would flash
' one on every logon, whatever window-style flag was passed.
Dim q, shell, cmd
q = Chr(34)
Set shell = CreateObject("WScript.Shell")
cmd = "cmd /c " & q & q & "$Python" & q & " -u " & q & "$agent" & q & _
      " >> " & q & "$log" & q & " 2>&1" & q
shell.Run cmd, 0, False
"@

Set-Content -Path $vbs -Value $vbsBody -Encoding ASCII

# The ABSOLUTE path to the host. "wscript.exe" alone can fail the task with
# 0x80070002 (file not found) even where the bare name resolves in a shell.
$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'

$action = New-ScheduledTaskAction -Execute $wscript `
    -Argument ('//B //Nologo "{0}"' -f $vbs) -WorkingDirectory $stateDir

$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

# Interactive, not S4U. See the note at the top: S4U breaks DPAPI, and the
# agent's vault credential is DPAPI-protected.
$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

# New-ScheduledTaskSettingsSet, not ...Settings - the shorter name does not
# exist, and the error says "not recognized as the name of a cmdlet", which
# reads like a missing module rather than a typo.
#
# ExecutionTimeLimit zero means no limit. Without it the task scheduler stops
# the agent after three days by default, and a service that quietly dies on
# the fourth day is worse than one that never started.
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

Write-Host "Registered '$TaskName'." -ForegroundColor Green
Write-Host "  host   : $wscript"
Write-Host "  shim   : $vbs"
Write-Host "  log    : $log"
Write-Host ''
Write-Host 'It starts at your next logon. Registering a task only means the'
Write-Host 'XML parsed, so check it actually ran:'
Write-Host '  (Get-ScheduledTaskInfo -TaskName "' -NoNewline
Write-Host $TaskName -NoNewline
Write-Host '").LastTaskResult     # 0 = ran'
Write-Host '  curl http://127.0.0.1:8091/healthz'

if ($StartNow) {
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 6
    $info = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host ''
    Write-Host ("Started now. LastTaskResult: {0}" -f $info.LastTaskResult)
}
