"""Regenerate shared/vault-vectors.json.

The vault envelope is a contract between two independently configured
implementations: Python seals a value here, and C# in `example/ai` stores it
and hands it back. A byte-copy cannot keep those honest the way
tools/sync-core.js keeps the JavaScript copies honest, so the guard is a
fixture both sides read - the same approach shared/test-vectors.json already
takes for token derivation.

What the fixture pins, and what each side asserts over it:

    Python  agent/tests/test_vault_vectors.py
            every row opens under the key and hashes back to its token.

    C#      tests/.../VaultVectorTests.cs in example/ai
            every row submits over real HTTP, survives Postgres, and comes
            back byte-identical.

Together those say: a value one machine sealed is one another machine can
open, after a real round trip through the real server. Neither half says
that alone.

Run it after any change to the envelope format, and expect both suites to
move together. If only one does, the vault silently stops resolving - which
looks exactly like a vault with nothing in it.

    python tools/gen-vault-vectors.py [--check]
"""

import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'proxy'))
sys.path.insert(0, os.path.join(ROOT, 'agent'))

import claudefuscator_core as core          # noqa: E402
import vault_crypto as vc                   # noqa: E402

TARGET = os.path.join(ROOT, 'shared', 'vault-vectors.json')
KEY = 'vault-vector-key'

# Invented values only - never real vocabulary, per the repo's rules. The
# last one is deliberately non-ASCII: it has to survive UTF-8 encoding here,
# base64, a varchar column, JSON serialisation and the trip back.
CASES = [
    ('IP',     '10.44.2.9',             'Widget'),
    ('HOST',   'build-01.corp.example', 'Widget'),
    ('PERSON', 'Jane Example',          None),
    ('PERSON', 'Jan Müller — Řež', None),
]


def build():
    rows = []
    for type_, value, product in CASES:
        token = core.derive_token(KEY, type_, value, 8)
        envelope = vc.seal(KEY, token, value, product=product)

        # Never emit a vector that does not satisfy what it is meant to pin.
        assert vc.open_envelope(KEY, token, envelope, product=product) == value
        assert vc.verify_token(KEY, token, value)

        rows.append({
            'token': token,
            'value': value,
            'product': product,
            'envelopeVersion': envelope['v'],
            'nonce': envelope['n'],
            'ciphertext': envelope['ct'],
        })

    return {
        '_comment': (
            'Cross-language contract for the vault envelope. Generated by '
            'tools/gen-vault-vectors.py; do not hand-edit. Python seals these; '
            'the C# server in example/ai stores and returns the same bytes; '
            'Python opens them again.'),
        'key': KEY,
        'tokenVersion': core.TOKEN_VERSION,
        'envelopeVersion': vc.ENVELOPE_VERSION,
        'rows': rows,
    }


def main():
    text = json.dumps(build(), indent=2, ensure_ascii=False) + '\n'

    if '--check' in sys.argv:
        # A nonce is fresh per seal, so the ciphertext differs every run and
        # the file can never be compared byte for byte. What --check answers
        # is the question that matters: does what is committed still open?
        if not os.path.exists(TARGET):
            print('shared/vault-vectors.json is missing', file=sys.stderr)
            return 1
        existing = json.loads(io.open(TARGET, encoding='utf-8').read())
        for row in existing['rows']:
            envelope = {'v': row['envelopeVersion'], 'n': row['nonce'],
                        'ct': row['ciphertext']}
            try:
                opened = vc.open_envelope(
                    existing['key'], row['token'], envelope, product=row['product'])
            except vc.VaultCryptoError as e:
                print(f'{row["token"]} no longer opens: {e}', file=sys.stderr)
                return 1
            if opened != row['value']:
                print(f'{row["token"]} opened to the wrong value', file=sys.stderr)
                return 1
        print(f'vault vectors OK ({len(existing["rows"])} rows)')
        return 0

    io.open(TARGET, 'w', encoding='utf-8', newline='\n').write(text)
    print(f'wrote {TARGET} ({len(build()["rows"])} rows)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
